name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test: # Nouveau nom pour refléter les tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Optimise la vitesse en cachant les modules

      - name: Install dependencies
        run: npm install
      
       # Linting avec correction automatique
      - name: Run ESLint
        run: |
          echo "Linting project..."
          npm run lint -- --fix

      # Tests unitaires avec Vitest
      - name: Run Unit Tests
        run: npx vitest run # Exécute les tests une seule fois et s'arrête

      # Build du projet
      - name: Build project
        run: npm run build

      # Upload de l'artefact pour GitHub Pages
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    needs: build-and-test # Le déploiement ne commence que si le job précédent réussit
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
